### PR TITLE
Plonk: code cleanup 

### PR DESCRIPTION
**Pull request by vesselinux**
Addresses issue #58

### CODE REVIEW

**Comment by dtebbs** [comment]
This seems ilke it should target the #62 branch.  Otherwise the `Files changed` tab includes changes ffrom all PRs and it's difficult to review.

**Comment by vesselinux** [comment]
> This seems ilke it should target the #62 branch. Otherwise the `Files changed` tab includes changes ffrom all PRs and it's difficult to review.

Rebased on `plonk` and dropped all commits not relevant to this one.

**Review by dtebbs — APPROVED** [review]
LGTM

**Comment by dtebbs** [comment]
I think this needs rebasing onto `origin/plonk`, then ready to merge.

**Comment by vesselinux** [comment]
> I think this needs rebasing onto `origin/plonk`, then ready to merge.

Hm, I thought it's already rebased cf. https://github.com/clearmatics/libsnark/pull/63#issuecomment-1199471199 . Am I wrong?

Regarding the merge, what is the usual practise: should I merge it or you?

**Comment by vesselinux** [comment]
> Hm, I thought it's already rebased cf. [#63 (comment)](https://github.com/clearmatics/libsnark/pull/63#issuecomment-1199471199) . Am I wrong?

I was wrong indeed. I hadn't updated my repo with the merge of PR #60 when creating this branch off `plonk`. Rebased on `plonk` now so it's fixed.

**Pull request merged**
