### PR TITLE
Plonk: moved function print_vector to libff

### PR DESCRIPTION
**Pull request by vesselinux**
Addresses Issue #59

### CODE REVIEW

**Review by dtebbs — CHANGES_REQUESTED** [review]
Please push the libff change and fix the CI, then re-request a review.

**Comment by vesselinux** [comment]
> Please push the libff change and fix the CI, then re-request a review.

Sorry, I am a bit confused how to push the changes to `libff`.

From within directory `libsnark/build` I see that this branch (`plonk-libff-print-vector-issue-59`) uses a version of `libff` that is different from the one on the server:

```
libsnark/build$ git diff
diff --git a/depends/libff b/depends/libff
index f9a588c0..6dee67e4 160000
--- a/depends/libff
+++ b/depends/libff
@@ -1 +1 @@
-Subproject commit f9a588c05ff803adef5b94a677a6eb37d7ea94cc
+Subproject commit 6dee67e4aa3d75200670f2cec8585f37b693f7f2

```
Yet when I `cd` inside `depends/libff` in order to push the actual changes, git says that the branch is up to date with `origin/develop` and there is nothing to commit:

```
libsnark/build$ cd ../depends/libff
libsnark/depends/libff$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean

libsnark/depends/libff$ git diff
libsnark/depends/libff$

```
Would appreciate some help! Thanks.

**Comment by vesselinux** [comment]
> Please push the libff change and fix the CI, then re-request a review.

Done.

**Comment by dtebbs** [comment]
Depends on clearmatics/libff#77 ?

**Pull request merged**
