### PR TITLE
Anemoi hash r1cs remove duplicate gadgets (depends on #76)

### PR DESCRIPTION
**Pull request by vesselinux**
Addresses https://github.com/clearmatics/libsnark/issues/77 , https://github.com/clearmatics/libsnark/pull/65#discussion_r992421012 , https://github.com/clearmatics/libsnark/pull/65#discussion_r992423162

### CODE REVIEW

**Review by dtebbs — APPROVED** [review]
LGTM

**Comment by dtebbs** [comment]
Will merge after #76

**Comment by dtebbs** [comment]
@vesselinux can you rebase this and the other anemoi branch please.

**Comment by vesselinux** [comment]
> @vesselinux can you rebase this and the other anemoi branch please.

Done.

**Pull request merged**
